export { default as TabView } from './tab-view'
export { default as About } from './about'
export { default as Skills } from './skills'
export { default as Projects } from './projects'
export { default as Contact } from './contact'
export { default as ProjectLink } from './project-link'